export const LOGIN_CUSTOMER = 'LOGIN_CUSTOMER';

export const LOGIN_RESTAURANT = 'LOGIN_RESTAURANT';

export const SIGNUP_CUSTOMER = 'SIGNUP_CUSTOMER';

export const SIGNUP_RESTAURANT = 'SIGNUP_RESTAURANT';

export const LOGOUT_CUSTOMER = 'LOGOUT_CUSTOMER';

export const LOGOUT_RESTAURANT = 'LOGOUT_RESTAURANT';

export const GET_USER_DETAILS = 'GET_USER_DETAILS';

export const GET_RESTAURANT_DETAILS = 'GET_RESTAURANT_DETAILS';

export const ERROR = 'ERROR';

export const RESTAURANT = 'RESTAURANT';

export const MANAGE_RESTAURANT = 'MANAGE_RESTAURANT';

export const MENU = 'MENU';

export const CART = 'CART';

export const ADD_CART = 'ADD_CART';

export const RMV_CART = 'RMV_CART';
