export const LOGIN_CUSTOMER = 'LOGIN_CUSTOMER';

export const LOGIN_RESTAURANT = 'LOGIN_RESTAURANT';

export const SIGNUP_CUSTOMER = 'SIGNUP_CUSTOMER';

export const SIGNUP_RESTAURANT = 'SIGNUP_RESTAURANT';

export const LOGOUT_CUSTOMER = 'LOGOUT_CUSTOMER';

export const LOGOUT_RESTAURANT = 'LOGOUT_RESTAURANT';

export const GET_USER_DETAILS = 'GET_USER_DETAILS';

export const POST_USER_DETAILS = 'POST_USER_DETAILS';

export const GET_RESTAURANT_DETAILS = 'GET_RESTAURANT_DETAILS';

export const FAVORITES = 'FAVORITES';

export const GET_FAVORITES = 'GET_FAVORITES';

export const MODE_RESTAURANTS = 'MODE_RESTAURANTS';

export const DIETARY_RESTAURANTS = 'DIETARY_RESTAURANTS';

export const ERROR = 'ERROR';

export const GET_ALL_RESTAURANT = 'GET_ALL_RESTAURANT';

export const RESTAURANT = 'RESTAURANT';

export const MANAGE_RESTAURANT = 'MANAGE_RESTAURANT';

export const MENU = 'MENU';

export const CART = 'CART';

export const ADD_CART = 'ADD_CART';

export const RMV_CART = 'RMV_CART';

export const CHECKOUT = 'CHECKOUT';

export const PLACE_ORDER = 'PLACE_ORDER';

export const UPDATE_ORDER = 'UPDATE_ORDER';

export const GET_ORDERS = 'GET_ORDERS';

export const GET_CUSTOMER_ORDERS = 'GET_CUSTOMER_ORDERS';
